name: NodeExecTest # ワークフローの名前

on:
  push: # pushイベントでトリガー
    branches: ["node-js"] # mainブランチへのpush時のみ実行

jobs:
  echoTest: # ジョブの名前
    runs-on: ubuntu-latest # Ubuntuの最新環境で実行
    defaults:
      run:
        working-directory: ./nodejs # デフォルトの作業ディレクトリをnodejsに設定
    steps: # ジョブ内のステップ（処理の単位）
      - name: Show list # ステップの名前
        run: ls -l # 現在のディレクトリの内容を表示
      - name: Checkout code # ステップの名前
        uses: actions/checkout@v2 # コードをチェックアウトするアクションを使用
      - name: Set up Node.js # ステップの名前
        uses: actions/setup-node@v2 # Node.jsをセットアップするアクションを使用
        with:
          node-version: "14" # Node.jsのバージョンを指定
      - name: Install dependencies # ステップの名前
        run: npm install # npmで依存関係をインストール
      - name: Run tests # ステップの名前
        run: npm start # npmでテストを実行
